server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatdb
    username: main
    password: main
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
jwt:
  # TODO: need complete jwt key
  secret: your_jwt_secret_key
  expiration: 86400000  # 24h